# Change these first
owner: fnzv # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: sa.mi.it
    url: https://sa.mi.it
  - name: sami.pw
    url: https://sami.pw
  - name: Telegram
    url: https://web.telegram.org
  - name: Whatsapp
    url: https://web.whatsapp.com
  - name: YT
    url: https://web.whatsapp.com
  - name: Twitter
    url: https://twitter.com
  - name: AWS Console
    url: https://console.aws.amazon.com
  - name: Contaboo
    url: https://my.contabo.com



status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: monitor.sa.mi.it
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Statuspage of some random services and stuff, if something is broken here maybe the internet or this CI is on fire"
  introMessage: Just looking 👀
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
